### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by lxqpku** [hhhusiyi-monash/UPDeT#3]
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    ex = Experiment("pymarl")
  File "/home/username/anaconda3/lib/python3.7/site-packages/sacred/experiment.py", line 75, in __init__
    _caller_globals=caller_globals)
  File "/home/username/anaconda3/lib/python3.7/site-packages/sacred/ingredient.py", line 57, in __init__
    gather_sources_and_dependencies(_caller_globals)
  File "/home/username/anaconda3/lib/python3.7/site-packages/sacred/dependencies.py", line 487, in gather_sources_and_dependencies
    sources = gather_sources(globs, experiment_path)
  File "/home/username/anaconda3/lib/python3.7/site-packages/sacred/dependencies.py", line 440, in get_sources_from_imported_modules
    return get_sources_from_modules(iterate_imported_modules(globs), base_path)
  File "/home/username/anaconda3/lib/python3.7/site-packages/sacred/dependencies.py", line 409, in get_sources_from_modules
    filename = os.path.abspath(mod.__file__)
  File "/home/username/anaconda3/lib/python3.7/posixpath.py", line 371, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Perhaps there's a problem about the path variable, how to solve it?
Thanks

**Comment by Theohhhu** [comment]
I recommend you check your environment configuration first. You may try [https://github.com/oxwhirl/pymarl](url). As our code is mainly based on them.

**Comment by lxqpku** [comment]
thanks for your reply, I've solved the problem
